version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-api-db
    environment:
      POSTGRES_DB: todo_api
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: nuevaClaveSegura123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-api-net

  app:
    build: .
    container_name: todo-api-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todo_api
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: nuevaClaveSegura123
    ports:
      - "8080:8080"
    networks:
      - todo-api-net

volumes:
  postgres_data:

networks:
  todo-api-net:

